# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7cf19af469e919384471035f8849e04c3462bdaf976fd98d4d7a3697ac4090c0156bbe5b4fae42ca2d502260b45bdf4deea3e1e0c4ae21f1f8f9f4595a64451

test:
  secret_key_base: 6f41fdc23476ad2800aa219fd45daeeb27113551800a03afcdecaf8d9640bac881cc160e300d1dac75e879490b404bbd98fa69ee7997e866b3982019f8996450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
